In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1., ])
type(arr[0])

numpy.float64

In [8]:
arr = np.zeros((2, 3), dtype=np.int32)
arr

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [9]:
arr = np.ones((2,3), dtype=np.int32)
arr

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [13]:
arr = np.array([[1,2,3], [4,5,6]])
arr = np.zeros_like(arr)
arr

array([[0, 0, 0],
       [0, 0, 0]])