In [1]:
import numpy as np
import pandas as pd

In [3]:
image = np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 100, 100, 100, 100, 100],
    [0, 0, 100, 100, 100, 100, 100],
    [0, 0, 100, 100, 100, 100, 100],
    [0, 0, 100, 100, 100, 100, 100],
    [0, 0, 100, 100, 100, 100, 100],    
])

In [5]:
image.shape

(9, 7)

In [6]:
hx = np.array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

hy = np.array([[-1, -2, -1],
       [ 0,  0,  0],
       [ 1,  2,  1]])

In [11]:
# image nhan tich chap cho hx
image_hx = np.zeros((image.shape[0]-2, image.shape[1]-2))
image_hx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# image nhan tich chap cho hy
image_hy = np.zeros((image.shape[0]-2, image.shape[1]-2))


image_hy

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# tri tuyet doi cua image_hx + tri tuyet doi cua image_hy
image_hx_hy = np.zeros((image.shape[0]-2, image.shape[1]-2))
image_hx_hy

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])